global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx-status'
    scrape_interval: 30s

  # Backend health metrics
  - job_name: 'ellie-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Frontend health metrics
  - job_name: 'ellie-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']